### ISSUE TITLE
Defaults File

### ISSUE THREAD

**Issue by spilth** [spilth/savant#9]
Allow defaults for `groupId`, `language` and `format` to be set in a `~/.savantrc` file.

For example:

```yaml
language: kotlin
groupId: org.spilth
format: gradle
```
